name: Build and Publish Web API
description: Build and Publish Web API
inputs:  
  build-configuration:
    description: 'Build configuration'
    required: true
    default: 'Release'
  dotnet-version:
    description: 'Dotnet version'
    required: true
    default: '8.x'
  project-file:
    description: 'Project file to build'
    required: true
    default: 'my-dotnet8-webapi.csproj'
  project-folder-path:
    description: 'Project file folder path'
    required: true
    default: 'pocpublic/my-dotnet8-webapi'

runs:
  using: composite
  steps:        
    - name: Restore dependencies
      shell: bash
      working-directory: ${{ inputs.project-folder-path }}
      run: dotnet restore
      
    - name: Build and Publish Web API project
      shell: bash
      working-directory: ${{ inputs.project-folder-path }}
      run: |
        dotnet build ${{ inputs.project-file }} --no-restore --configuration ${{ inputs.build-configuration}}
        dotnet publish ${{ inputs.project-file }} --no-build --configuration ${{ inputs.build-configuration}} --output ./publish/${{ inputs.build-configuration}}
      
    - name: Test
      shell: bash
      working-directory: ${{ inputs.project-folder-path }}
      run: dotnet test --no-build --verbosity normal
