name: Deploy my-dotnet8-webapi

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies
        run: dotnet restore my-dotnet8-webapi/my-dotnet8-webapi.csproj

      - name: Build the project
        run: dotnet build my-dotnet8-webapi/my-dotnet8-webapi.csproj --configuration Release --no-restore

      - name: Publish the project
        run: dotnet publish my-dotnet8-webapi/my-dotnet8-webapi.csproj --configuration Release --output ./publish

      - name: Archive files for deployment
        run: zip -r my-dotnet8-webapi.zip ./publish

      - name: Log in to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy to Azure Web App
        uses: Azure/webapps-deploy@v3
        with:
          app-name: 'app-cospapi-case-pocpublic' # Replace with your Web App name
          package: './my-dotnet8-webapi.zip'
          resource-group-name: 'POC' # Replace with your resource group name
          type: 'ZIP'