environment:
  name: Development
  short_name: dev
  
azure:
  # Web API configuration
  webapp_name: app-cospapi-case-pocpublic-dev
  resource_group: POC
  subscription_id: "#{AZURE_SUBSCRIPTION_ID}#"
  location: "South India"
  
  # Azure Functions configuration
  function_app_name: fatestpoc
  function_app_resource_group: POC

  # Logic App configuration
  logic_app_name: lapoctest01
  logic_app_resource_group: POC
  logic_app_workflow_name: FileConversion
  
app_settings:
  ASPNETCORE_ENVIRONMENT: Development
  WEBSITE_RUN_FROM_PACKAGE: "1"
  
connection_strings:
  DefaultConnection:
    value: "#{ConnectionString-Development}#"
    type: SQLServer
  
logging:
  level: Debug
  enable_application_insights: true
  application_insights_key: "#{AppInsights-Key-Dev}#"