name: Deploy Azure Logic App

on:
  workflow_dispatch:
    inputs:
      environment:
        description: Target environment
        required: true
        type: choice
        options:
          - Development
          - Testing
          - Acceptance
          - Production

permissions:
      id-token: write
      contents: read

env:
  PATH_REPO: ./
  PROJECT_FOLDER_PATH: CoSP.LogicApps
  WORKFLOW_NAME: FileConversion
  LOGIC_APP_NAME: lapoctest01
  RESOURCE_GROUP: poc

jobs:
  deploy-to-target-environment:
    name: Deploy to ${{ github.event.inputs.environment }} environment
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.environment }}
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          path: ${{ env.PATH_REPO }}
          lfs: false
      
      - name: Set Target Environment tag
        run: |
          case "${{ github.event.inputs.environment }}" in
            Development) echo "TARGET_ENV_SHORT=dev" >> $GITHUB_ENV;;
            Testing)     echo "TARGET_ENV_SHORT=tst" >> $GITHUB_ENV;;
            Staging)  echo "TARGET_ENV_SHORT=acc" >> $GITHUB_ENV;;
            Production)  echo "TARGET_ENV_SHORT=prd" >> $GITHUB_ENV;;
            *)           echo "Unknown environment"; exit 1;;
          esac          
      

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Build Logic App code
        run: |
          echo "Building Logic App workflow package"
          cd ${{ env.PATH_REPO }}/${{ env.PROJECT_FOLDER_PATH }}
          
          # The zip should contain the workflow folder and its contents
          zip -r workflow.zip ${{ env.WORKFLOW_NAME }}/
          ls -la workflow.zip


      - name: Configure Logic App Settings
        run: |
          echo "Configuring Logic App Settings for ${{ env.LOGIC_APP_NAME }}"
          
          # Set basic Logic App settings
          az logicapp config appsettings set \
            --name "${{ env.LOGIC_APP_NAME }}" \
            --resource-group "${{ env.RESOURCE_GROUP }}" \
            --settings \
              WORKFLOWS_LOCATION_NAME="${{ env.TARGET_ENV_SHORT }}" \
              AZURE_CLIENT_ID="${{ secrets.AZURE_CLIENT_ID }}"

      - name: Deploy Logic App Standard code
        run: |
          echo "Deploying Logic App: ${{ env.LOGIC_APP_NAME }}"
          
          az logicapp deployment source config-zip \
            --name "${{ env.LOGIC_APP_NAME }}" \
            --resource-group "${{ env.RESOURCE_GROUP }}" \
            --src "${{ env.PROJECT_FOLDER_PATH }}/workflow.zip"

      - name: Confirm deployment
        run: |
          echo "🎉 Successfully deployed Logic App: ${{ env.LOGIC_APP_NAME }}"

      - name: logout
        run: |
          az logout