name: Deploy Web API Infrastructure

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy Bicep file
        run: |
          az deployment group create \
            --resource-group POC \
            --template-file infra/azureInfraDeployment.bicep \
            --parameters appServicePlanName=app-cospapi-case-pocpublic \
                        webAppName=app-cospapi-case-pocpublic \
                        repoUrl=https://github.com/boseamalita/pocpublic.git \
                        branch=main \