name: .NET Core

on: [push]

permissions:
      id-token: write
      contents: read

env:
  AZURE_WEBAPP_NAME: app-cospapi-case-pocpublic01    # Set this to your application's name
  AZURE_WEBAPP_PACKAGE_PATH: './my-dotnet8-webapi'     # Update this to the correct path to your project
  DOTNET_VERSION: '8.0.x'                # Set this to the dot net version to use

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Check out the
      - uses: actions/checkout@main
      - uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_8CDB4B14E9F143C08C123D9DA20DC52B }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_0333DBF453E14A7085FBE5F0340EC9B9 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_9CEA50D29A4648CDAB4F4BE360A3CE68 }}

      # Setup .NET Core SDK
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }} 
      
      # Run dotnet build and publish
      - name: dotnet build and publish
        run: |
          cd ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
          dotnet restore
          dotnet build --configuration Release
          mkdir -p app-cospapi-case-pocpublic  # Ensure the directory exists
          dotnet publish -c Release --output app-cospapi-case-pocpublic
      
      # Debugging step to ensure files exist
      - name: Debug - List Published Files
        run: |
          ls -la ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}/app-cospapi-case-pocpublic
      
      # Deploy to Azure Web apps
      - name: 'Run Azure webapp deploy action using publish profile credentials'
        uses: azure/webapps-deploy@v3
        with: 
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          package: '${{ env.AZURE_WEBAPP_PACKAGE_PATH }}/app-cospapi-case-pocpublic'
      
      - name: logout
        run: |
          az logout