name: Deploy FODJ CoSP Logic App

on:
  workflow_dispatch:
    inputs:
      environment:
        description: Target environment
        required: true
        type: choice
        options:
          - Development
          - Testing
          - Acceptance
          - Production

permissions:
      id-token: write
      contents: read

env:
  PATH_REPO: ./
  PROJECT_FOLDER_PATH: JMP.CoSP/JMP.CoSP.FileServices
  WORKFLOW_NAME: FileConversion
  LOGIC_APP_NAME: lapoctest01
  PATH_DEPLOY: deploy

jobs:
  deploy-to-target-environment:
    name: Deploy to ${{ github.event.inputs.environment }} environment
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.environment }}
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          path: ${{ env.PATH_REPO }}
          lfs: false
      
      - name: Set Target Environment tag
        run: |
          case "${{ github.event.inputs.environment }}" in
            Development) echo "TARGET_ENV_SHORT=dev" >> $GITHUB_ENV;;
            Testing)     echo "TARGET_ENV_SHORT=tst" >> $GITHUB_ENV;;
            Staging)  echo "TARGET_ENV_SHORT=acc" >> $GITHUB_ENV;;
            Production)  echo "TARGET_ENV_SHORT=prd" >> $GITHUB_ENV;;
            *)           echo "Unknown environment"; exit 1;;
          esac          
      

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      
      ## Build installation zip file for logic app
      - name: Package logic app from sources
        run: |
          mkdir -p ${{ env.PATH_DEPLOY }}

          cp -r ${{ env.PATH_REPO }}/${{ env.PROJECT_FOLDER_PATH }}/workflows/* ${{ env.PATH_DEPLOY }}
          cp ${{ env.PATH_REPO }}/${{ env.PROJECT_FOLDER_PATH }}/parameters/parameters_${{ env.TARGET_ENV_SHORT }}.json ${{ env.PATH_DEPLOY }}/parameters.json

          ls -la

          ls -la ${{ env.PATH_DEPLOY }}

          cd ${{ env.PATH_DEPLOY }}
          zip -r ../to_deploy.zip .
          cd ..

      - name: Upload the deployment zip to artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.LOGIC_APP_NAME }}
          path: to_deploy.zip
          overwrite: true

      - name: Deploy logic app zip to target azure environment
        uses: azure/functions-action@v1
        with:
          app-name: '${{ env.LOGIC_APP_NAME }}'
          package: workflow.zip

      - name: Build Logic App code
        run: |
          echo "Building Logic App workflow package"
          cd ${{ env.PATH_REPO }}/${{ env.PROJECT_FOLDER_PATH }}
          
          # The zip should contain the workflow folder and its contents
          zip -r workflow.zip ${{ env.WORKFLOW_NAME }}/
          ls -la workflow.zip

      - name: Confirm deployment
        run: |
          echo "🎉 Successfully deployed Logic App: ${{ env.LOGIC_APP_NAME }}"

      - name: logout
        run: |
          az logout